apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-lab
  labels:
    app: k8s-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-lab
  template:
    metadata:
      labels:
        app: k8s-lab
    spec:
      containers:
      - name: k8s-lab
        image: k8s-lab:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
